/* ---------------- Research page (per addiction, EN/ES, ~20 lines each) ---------------- */

const RESEARCH = {
  Technology: {
    en: [
      "Define a clear screen-time rule (e.g., ≤2h/day, no phone in bedroom). Written rules increase adherence.",
      "Turn off nonessential notifications; batch the rest (cues drive compulsions).",
      "Move the phone charger outside the bedroom; use an analog alarm.",
      "Create app barriers: remove logins, uninstall 2 worst offenders, keep them off the home screen.",
      "Use focus modes and site blockers during work/bedtime (defaults shape behavior).",
      "Plan 3 daily replacements for scrolling: a walk, a call, 10 minutes of reading.",
      "Practice ‘one-tab rule’: finish a task before opening another (reduces task-switching costs).",
      "Urge surfing: watch the itch for 2–3 minutes while breathing; cravings crest and fall.",
      "Delay rule: wait 5 minutes, then choose deliberately; this weakens automaticity.",
      "Implement ‘screen sabbath’ blocks (e.g., 8–10pm no personal screens).",
      "Put the phone out of reach when working; use a timer (25/5 Pomodoro).",
      "Instrument your day: set calendar reminders for breaks and wind-down.",
      "Track daily Success/Slip on the calendar; self-monitoring boosts control.",
      "Share your goal and weekly screenshot with one ally; accountability helps.",
      "Replace dopamine hits: micro-workouts, sunlight, quick journaling.",
      "Protect sleep: blue-light filters off after 9pm and no screens in bed.",
      "Identify high-risk contexts (bed, couch, bathroom) and place friction there.",
      "When you slip, log trigger → lesson → one action now; iterate, not shame.",
      "Celebrate specific wins (e.g., ‘3 evenings phone-free’).",
      "If compulsive use persists, consider CBT/DBT skills training or coaching."
    ],
    es: [
      "Define una regla clara de pantalla (p. ej., ≤2 h/día, sin teléfono en el dormitorio). Las reglas escritas mejoran la adherencia.",
      "Apaga notificaciones no esenciales; agrupa el resto (las señales impulsan la compulsión).",
      "Coloca el cargador fuera del dormitorio; usa un despertador analógico.",
      "Crea barreras: cierra sesiones, desinstala 2 apps problemáticas, quítalas de la pantalla principal.",
      "Usa modos de concentración y bloqueadores en trabajo/antes de dormir (los predeterminados moldean la conducta).",
      "Planifica 3 reemplazos diarios del desplazamiento: caminar, llamar, leer 10 minutos.",
      "‘Regla de una pestaña’: termina una tarea antes de abrir otra.",
      "Surf del impulso: observa el picor 2–3 min mientras respiras; el antojo sube y baja.",
      "Regla de demora: espera 5 minutos y decide con intención; debilita la automaticidad.",
      "Bloques de ‘sábado digital’ (p. ej., 20–22 h sin pantallas personales).",
      "Teléfono fuera del alcance al trabajar; usa temporizador (25/5 Pomodoro).",
      "Estructura el día: recordatorios para pausas y rutina nocturna.",
      "Registra Logro/Recaída en el calendario; el automonitoreo ayuda.",
      "Comparte tu objetivo y captura semanal con un aliado; la responsabilidad ayuda.",
      "Sustituye el dopaje: micro-ejercicios, luz solar, escritura breve.",
      "Protege el sueño: sin filtros de luz azul después de las 21 h y sin pantallas en la cama.",
      "Detecta contextos de riesgo (cama, sofá, baño) y añade fricción allí.",
      "Si recaes, anota disparador → lección → una acción ahora; iterar sin culpa.",
      "Celebra logros concretos (p. ej., ‘3 noches sin teléfono’).",
      "Si persiste el uso compulsivo, considera TCC/entrenamiento en habilidades DBT."
    ]
  },
  Smoking: {
    en: [
      "Pick a quit date within 7–14 days; tell one supportive person (commitment increases success).",
      "Start Nicotine Replacement Therapy (patch + gum/lozenge) on quit day per instructions.",
      "Map triggers (coffee, car, stress); pair each with a substitute (water, walk, breathing).",
      "Clean your environment: wash clothes, remove lighters/ashtrays; fresh start matters.",
      "Use the 5-minute delay + long exhale (parasympathetic activation reduces urge).",
      "Mouth/hand plan: sugar-free gum, straws, toothpicks, stress ball.",
      "Plan caffeine adjustments (caffeine can feel stronger after quitting).",
      "Write a refusal script for offers: “No thanks, I’m quitting.”",
      "Walk 10–15 minutes daily; exercise reduces withdrawal symptoms.",
      "Log urges (time/intensity/what you did); turn cravings into data.",
      "Hydrate and snack fruit/veggies to manage oral fixation and blood sugar.",
      "Sleep routine: consistent schedule; fatigue worsens cravings.",
      "Avoid alcohol early—it weakens inhibition and cues smoking.",
      "Use apps/counters to see streaks and money saved; reward milestones.",
      "If you slip, treat it as a lapse, not a collapse; recommit immediately.",
      "Consider group/phone counseling—evidence shows higher quit rates.",
      "Keep NRT handy for high-risk windows (commute, breaks).",
      "Ask a clinician about meds (varenicline/bupropion) if needed.",
      "Track daily Success/Slip on the calendar; review weekly with ally.",
      "Celebrate smoke-free days with a meaningful, non-food reward."
    ],
    es: [
      "Elige una fecha para dejar en 7–14 días; cuéntaselo a alguien que te apoye.",
      "Inicia Terapia Sustitutiva de Nicotina (parche + chicle/pastilla) el día de dejar, según indicaciones.",
      "Mapea disparadores (café, coche, estrés) y asigna sustitutos (agua, caminar, respirar).",
      "Limpia el entorno: lava ropa, retira encendedores/ceniceros.",
      "Regla de 5 minutos + exhalación larga (activa el parasimpático y baja el deseo).",
      "Plan boca/manos: chicle sin azúcar, pajitas, palillos, pelota antiestrés.",
      "Ajusta cafeína (puede sentirse más fuerte al dejar).",
      "Prepara un guion de rechazo: “No gracias, lo estoy dejando”.",
      "Camina 10–15 min diarios; el ejercicio reduce síntomas de abstinencia.",
      "Registra impulsos (hora/intensidad/qué hiciste); convierte el antojo en datos.",
      "Hidrátate y come fruta/verdura para la fijación oral y la glucosa.",
      "Rutina de sueño constante; el cansancio empeora los antojos.",
      "Evita alcohol al inicio—disminuye el autocontrol y dispara fumar.",
      "Usa apps/contadores para ver rachas y dinero ahorrado; recompensa hitos.",
      "Si resbalas, trátalo como lapsus, no colapso; recomponte de inmediato.",
      "Considera consejería/llamadas: mayor tasa de éxito según evidencia.",
      "Ten TSN a mano en ventanas de riesgo (traslados, descansos).",
      "Consulta sobre fármacos (vareniclina/bupropión) si hace falta.",
      "Registra Logro/Recaída en el calendario; revisa semanalmente.",
      "Celebra días sin fumar con una recompensa significativa."
    ]
  },
  Alcohol: {
    en: [
      "Decide: abstinence or a weekly cap; write a one-sentence commitment.",
      "Remove alcohol from home; stock appealing NA options.",
      "Plan ‘first drink’ alternatives: NA in your glass when others order.",
      "Scripts for offers: “I'm taking a break—NA for me tonight.”",
      "Use HALT check (Hungry/Angry/Lonely/Tired) before decisions.",
      "Schedule evening routine: meal → walk → shower → wind-down.",
      "Delay urges 5 minutes while slow breathing; urge surfing 2–3 min.",
      "Avoid high-risk contexts early (happy hour, certain friends).",
      "Arrange accountability: weekly check-ins with one trusted person.",
      "Track units if moderating; pre-commit max per event and pace with water.",
      "Protect sleep; alcohol fragments it and increases next-day cravings.",
      "Identify trigger chains (stress → bar route) and reroute.",
      "If a lapse occurs, hydrate, eat, sleep, and write one lesson.",
      "Use contingency rewards for sober streaks (behavioral reinforcement).",
      "Practice refusal skills out loud; confidence reduces impulsive yes.",
      "Plan transport and a leaving time; exit early if cues pile up.",
      "Replace dopamine: exercise, music, creativity, social connection.",
      "Consider therapy/meds (naltrexone/acamprosate) with a clinician.",
      "Mark daily Success/Slip; review weekly trends and adjust.",
      "Celebrate alcohol-free weeks with something meaningful."
    ],
    es: [
      "Decide: abstinencia o tope semanal; escribe un compromiso en una frase.",
      "Retira alcohol de casa; almacena opciones sin alcohol atractivas.",
      "Alternativa al ‘primer trago’: bebida sin alcohol en tu vaso cuando otros pidan.",
      "Guiones para ofertas: “Estoy en un descanso—para mí sin alcohol”.",
      "Usa HALT (Hambre/Enojo/Soledad/Cansancio) antes de decidir.",
      "Rutina nocturna: cena → caminata → ducha → relajación.",
      "Demora 5 minutos con respiración lenta; surf del impulso 2–3 min.",
      "Evita contextos de alto riesgo al inicio (happy hour, ciertas compañías).",
      "Arma responsabilidad: chequeos semanales con alguien de confianza.",
      "Si moderas, registra unidades; pre-compromete un máximo y alterna con agua.",
      "Protege el sueño; el alcohol lo fragmenta y aumenta antojos al día siguiente.",
      "Detecta cadenas de disparadores (estrés → ruta al bar) y redirígelas.",
      "Si hay lapsus: hidrátate, come, duerme, y escribe una lección.",
      "Usa recompensas por rachas sobrias (refuerzo conductual).",
      "Practica rechazos en voz alta; la confianza reduce el ‘sí’ impulsivo.",
      "Planifica transporte y hora de salida; retírate si se acumulan señales.",
      "Sustituye dopamina: ejercicio, música, creatividad, conexión social.",
      "Considera terapia/fármacos (naltrexona/acamprosato) con un profesional.",
      "Marca Logro/Recaída diaria; revisa tendencias y ajusta.",
      "Celebra semanas sin alcohol con algo significativo."
    ]
  },
  Gambling: {
    en: [
      "Self-exclude from online platforms; request bank gambling blocks.",
      "Install device blockers/DNS filters across all devices.",
      "Create a budget firewall: separate essentials account inaccessible for gambling.",
      "Share statements weekly with a trusted person (accountability).",
      "Identify high-risk windows (payday, sports events) and pre-plan alternatives.",
      "Delay 10 minutes + urge surfing when cravings spike.",
      "Remove betting apps and browser shortcuts; add friction to deposits.",
      "Carry limited cash; freeze cards or keep them with an ally on risky days.",
      "Replace excitement with safe dopamine: exercise, games without money, volunteering.",
      "Avoid tip groups/streams; mute keywords and leave betting chats.",
      "Schedule evenings with structured, low-stimulation activities.",
      "Track triggers and spending urges in a log; make costs visible.",
      "If a lapse occurs, cap losses immediately, contact your ally, review triggers.",
      "Set meaningful rewards for non-gambling weeks.",
      "Block access in physical venues if available (self-ban).",
      "Build a debt plan if needed; face numbers with support.",
      "Attend support groups/counseling; outcomes improve with guidance.",
      "Use the calendar to mark Success/Slip and review weekly patterns.",
      "Practice visualization: leaving after first cue; rehearse exits.",
      "Protect sleep and stress load—both elevate risk of betting."
    ],
    es: [
      "Auto-exclúyete de plataformas; solicita bloqueos bancarios para juego.",
      "Instala bloqueadores/DNS en todos los dispositivos.",
      "Crea un ‘cortafuegos’ de presupuesto: cuenta de esenciales inaccesible para apostar.",
      "Comparte extractos semanalmente con alguien de confianza (responsabilidad).",
      "Identifica ventanas de alto riesgo (día de pago, eventos deportivos) y pre-planea alternativas.",
      "Demora 10 minutos + surf del impulso cuando suba el deseo.",
      "Elimina apps y accesos directos; añade fricción a los depósitos.",
      "Lleva efectivo limitado; congela tarjetas o déjalas con un aliado en días críticos.",
      "Sustituye la excitación con dopamina segura: ejercicio, juegos sin dinero, voluntariado.",
      "Evita grupos/streams de ‘tips’; silencia palabras clave y abandona chats de apuestas.",
      "Agenda tardes con actividades estructuradas y de baja estimulación.",
      "Registra disparadores y ganas de gasto; haz visibles los costos.",
      "Si hay lapsus, limita pérdidas de inmediato, contacta al aliado y revisa disparadores.",
      "Define recompensas por semanas sin apostar.",
      "Bloquea acceso en locales físicos si existe (auto-prohibición).",
      "Si hay deudas, crea un plan; afronta números con apoyo.",
      "Asiste a grupos/terapia; los resultados mejoran con guía.",
      "Usa el calendario para marcar Logro/Recaída y revisar patrones.",
      "Practica visualización: irte tras la primera señal; ensaya salidas.",
      "Protege sueño y estrés—ambos elevan el riesgo de apostar."
    ]
  }
};

function researchText(){
  const a = state.profile?.primary || "Technology";
  const L = document.documentElement.getAttribute("data-lang") || "en";
  const lines = (RESEARCH[a] && RESEARCH[a][L]) ? RESEARCH[a][L] : RESEARCH.Technology.en;
  const list = lines.map(x=>`<li>${x}</li>`).join("");
  return `<h3 class="fancy">${t("researchTitle")} — ${translateAddiction(a)}</h3><ol class="program">${list}</ol><p class="muted">${t("footer")}</p>`;
}
function renderResearch(){ $("#researchBody").innerHTML = researchText(); }
